export default function PagePrivacidad() {
    return (
        <div className="w-full flex justify-center items-center">
            <div className="w-4/6 flex justify-center items-center flex-col overflow-auto">
                <p className="text-3xl sm:text-5xl mb-6 font-semibold">Política de privacidad</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Usuario y régimen de responsabilidades</p>
                <p className="sm:text-2xl font-extralight mb-4">La navegación, acceso y uso por el sitio web de Patatas Gourmet SL confiere la condición de usuario, por la que se aceptan, desde la navegación por el sitio web de Patatas Gourmet SL, todas las condiciones de uso aquí establecidas sin perjuicio de la aplicación de la correspondiente normativa de obligado cumplimiento legal según el caso.</p>
                <p className="sm:text-2xl font-extralight mb-4">El sitio web de Patatas Gourmet SL proporciona gran diversidad de información, servicios y datos. El usuario asume su responsabilidad en el uso correcto del sitio web. Esta responsabilidad se extenderá a:</p>
                <p className="sm:text-2xl font-extralight mb-4 ml-10">La veracidad y licitud de las informaciones aportadas por el usuario en los formularios extendidos por Patatas Gourmet SL para el acceso a ciertos contenidos o servicios ofrecidos por el web.</p>
                <p className="sm:text-2xl font-extralight mb-4 ml-10">El uso de la información, servicios y datos ofrecidos por Patatas Gourmet SL contrariamente a lo dispuesto por las presentes condiciones, la Ley, la moral, las buenas costumbres o el orden público, o que de cualquier otro modo puedan suponer lesión de los derechos de terceros o del mismo funcionamiento del sitio web.</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Política de enlaces y exenciones de responsabilidad</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL no se hace responsable del contenido de los sitios web a los que el usuario pueda acceder a través de los enlaces establecidos en su sitio web y declara que en ningún caso procederá a examinar o ejercitar ningún tipo de control sobre el contenido de otros sitios de la red.</p>
                <p className="sm:text-2xl font-extralight mb-4">Asimismo, tampoco garantizará la disponibilidad técnica, exactitud, veracidad, validez o legalidad de sitios ajenos a su propiedad a los que se pueda acceder por medio de los enlaces.</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL declara haber adoptado todas las medidas necesarias para evitar cualquier daño a los usuarios de su sitio web, que pudieran derivarse de la navegación por su sitio web. En consecuencia,</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL no se hace responsable, en ningún caso, de los eventuales daños que por la navegación por Internet pudiera sufrir el usuario.</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Modificaciones</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL se reserva el derecho a realizar las modificaciones que considere oportunas, sin aviso previo, en el contenido de su sitio web. Tanto en lo referente a los contenidos del sitio web, como en las condiciones de uso del mismo.</p>
                <p className="sm:text-2xl font-extralight mb-4">Dichas modificaciones podrán realizarse a través de su sitio web por cualquier forma admisible en derecho y serán de obligado cumplimiento durante el tiempo en que se encuentren publicadas en la web y hasta que no sean modificadas válidamente por otras posteriores.</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Protección de datos</p>
                <p className="sm:text-2xl font-extralight mb-4">De conformidad con lo que establece la Ley Orgánica 15/1999 de Protección de Datos de Carácter Personal (LOPD), Patatas Gourmet SL informa a los usuarios de su sitio web que los datos personales recabados por la empresa, mediante los formularios sitos en sus páginas, serán introducidos en un fichero automatizado bajo la responsabilidad de Patatas Gourmet SL, con la finalidad de poder facilitar, agilizar y cumplir los compromisos establecidos entre ambas partes.</p>
                <p className="sm:text-2xl font-extralight mb-4">Asimismo, Patatas Gourmet SL informa de la posibilidad de ejercer los derechos de acceso, rectificación, cancelación y oposición mediante un escrito a la dirección: C/ El Comercio, 12, 14910, Benamejí (Córdoba).</p>
                <p className="sm:text-2xl font-extralight mb-4">Mientras el usuario no comunique lo contrario a Patatas Gourmet SL, esta entenderá que sus datos no han sido modificados, que el usuario se compromete a notificar a Patatas Gourmet SL cualquier variación y que Patatas Gourmet SL tiene el consentimiento para utilizarlos a fin de poder fidelizar la relación entre las partes.</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Propiedad intelectual e industrial</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL por sí misma o como cesionaria, es titular de todos los derechos de propiedad intelectual e industrial de su página web, así como de los elementos contenidos en la misma (a título enunciativo, imágenes, sonido, audio, vídeo, software o textos; marcas o logotipos, combinaciones de colores, estructura y diseño, selección de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.), titularidad de Patatas Gourmet SL. Serán, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jurídico español, siéndoles aplicables tanto la normativa española y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por España.</p>
                <p className="sm:text-2xl font-extralight mb-4">Todos los derechos reservados. En virtud de lo dispuesto en los artículos 8 y 32.1, párrafo segundo, de la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducción, la distribución y la comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de esta página web, con fines comerciales, en cualquier soporte y por cualquier medio técnico, sin la autorización de Patatas Gourmet SL.</p>
                <p className="sm:text-2xl font-extralight mb-4">El usuario se compromete a respetar los derechos de Propiedad Intelectual e Industrial titularidad de Patatas Gourmet SL. Podrá visualizar los elementos del portal e incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre y cuando sea, única y exclusivamente, para su uso personal y privado. El usuario deberá abstenerse de suprimir, alterar, eludir o manipular cualquier dispositivo de protección o sistema de seguridad que estuviera instalado en las páginas de Patatas Gourmet SL.</p>
                <p className="text-2xl sm:text-3xl font-semibold mb-4">Acciones legales, legislación aplicable y jurisdicción</p>
                <p className="sm:text-2xl font-extralight mb-4">Patatas Gourmet SL se reserva, asimismo, la facultad de presentar las acciones civiles o penales que considere oportunas por la utilización indebida de su sitio web y contenidos, o por el incumplimiento de las presentes condiciones.</p>
                <p className="sm:text-2xl font-extralight mb-4">La relación entre el usuario y el prestador se regirá por la normativa vigente y de aplicación en el territorio español. De surgir cualquier controversia las partes podrán someter sus conflictos a arbitraje o acudir a la jurisdicción ordinaria cumpliendo con las normas sobre jurisdicción y competencia al respecto. Patatas Gourmet SL tiene su domicilio en Córdoba, España.</p>
            </div>
        </div>
    );
}